- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/components/common/Button.tsx
- src/components/layout/MainLayout.tsx
- src/components/layout/Navbar.tsx
- src/main.tsx
- src/pages/Login/index.tsx
- src/routes/index.tsx
- src/styles/index.css
> fix: 페이지 라우팅 해결

- src/components/common/Modal.tsx
- src/pages/MyPage/MyPage.tsx
feat: 모달 기능 추가
fix: 마이페이지에 모달 띄우는 기능 추가
#20 #21 
1. 공통 모달 컴포넌트 추가
2. 마이페이지에서 각 아이템 클릭시 발생하는 액션 추가
3. 마이페이지에 보관인 등록과 회원탈퇴 모달 부착
> feat: 모달 기능 추가 fix: 마이페이지에 모달 띄우는 기능 추가

- src/components/layout/BottomNavigation.tsx
- src/components/layout/Header.tsx
- src/pages/MyPage/MyPage.tsx
- src/pages/MyPlace/MyPlace.tsx
- src/pages/MyTrade/MyTrade.tsx
- src/pages/StorageDetail/StorageDetail.tsx
- src/pages/StorageList/StorageList.tsx
- src/routes/index.tsx
feat: 보관소 상세페이지 추가
fix: 헤더, 네비게이션 수정, 전체 페이지 레이아웃 수정
#11 #24 
1. 보관소 상세페이지 추가
2. 헤더에 드롭다운 기능 추가
3. 헤더와 하단 네비게이션 기능 수정
4. 전체 페이지 레이아웃 디테일 수정
> feat: 보관소 상세페이지 추가 fix: 헤더, 네비게이션 수정, 전체 페이지 레이아웃 수정

- package-lock.json
- package.json
- src/pages/EditStorage/EditStorage.tsx
- src/pages/Home/MapBottomSheet.tsx
- src/pages/MyPage/MyPage.tsx
- src/pages/MyPlace/MyPlace.tsx
- src/pages/StorageList/StorageFilterModal.tsx
- src/pages/StorageList/StorageList.tsx
- src/routes/index.tsx
feat: 보관장소수정, 바텀시트추가, 장소필터모달추가
#12 #27
1. 보관 장소 수정 페이지 제작
2. 바텀시트 제작 (테스트용으로 mypage에 추가)
3. 장소 리스트에 필터 모달 추가
> feat: 보관장소수정, 바텀시트추가, 장소필터모달추가

- package-lock.json
- package.json
- src/api/chat.ts
- src/components/layout/MainLayout.tsx
- src/pages/Chat/ChatroomList.tsx
- src/pages/Keeper/KeeperRegistration.tsx
- src/pages/MyPage/MyPage.tsx
- src/routes/index.tsx
feat: 보관인 등록 페이지 제작.
fix: 채팅목록에 채팅방 나가기 모달 및 api 추가
#14 #26 
1. 보관인 등록 페이지 레이아웃 제작
2. 채팅목록에 채팅방 나가기 모달 제작
3. 채팅 목록 불러오기 관련 api 추가(채팅목록 삭제 포함)
> feat: 보관인 등록 페이지 제작. fix: 채팅목록에 채팅방 나가기 모달 및 api 추가

- src/pages/StorageDetail/StorageDetail.tsx
fix: 보관소 상세정보에 이미지 슬라이더 기능 추가
1. 보관함 상세정보에 이미지 슬라이더 기능 추가
2. 슬라이더 indicator 클릭해도 이미지 이동 가능
3. indicator 클릭을 쉽게 하기 위해 dot 크기 증가
> fix: 보관소 상세정보에 이미지 슬라이더 기능 추가

- public/index.html
- src/components/map/KakaoMap.tsx
- src/pages/Home/index.tsx
- src/pages/StorageDetail/StorageDetail.tsx
<h3>Description</h3>
<p>Kakao Map 페이지를 추가하고, 홈 및 맵 화면의 BottomSheet 관련 버그를 수정했습니다.</p>
<h3>Related Issues</h3>
<ul>
<li>Resolves #123</li>
</ul>
<h3>Changes Made</h3>
<ol>
<li><code inline="">KakaoMap.tsx</code> 컴포넌트 추가 (카카오 지도 연동)</li>
<li><code inline="">home</code> 및 <code inline="">map</code> 화면에서 BottomSheet UI 버그 수정</li>
<li>관련 스타일 및 상태 관리 로직 개선</li>
<h3>Testing</h3>
<ol>
<li><code inline="">home</code> 및 <code inline="">map</code> 페이지에서 BottomSheet가 정상적으로 동작하는지 확인</li>
<li>Kakao Map이 올바르게 로드되고 인터랙션이 가능한지 테스트</li>
<li>크로스 브라우징 테스트 (Chrome, Safari, Edge)</li>
</ol>
<h3>Checklist</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" checked="" disabled=""> 코드가 정상적으로 컴파일되는지 확인했습니다.</li>
<li class="task-list-item"><input type="checkbox" checked="" …
> feat(kakaomap): Add new Kakao Map page

- src/pages/Keeper/KeeperRegistration.tsx
- src/pages/Map/SearchAddress.tsx
- src/pages/Registration/Registration1.tsx
feat: 주소 검색 페이지 추가
fix: 보관인등록 뒤로가기 개선, 보관소 등록에 주소검색 바인딩
1. 주소 검색 페이지 추가
2. 보관소 등록1에 주소 검색 페이지 바인딩
3. 보관소 등록 로직 개선
4. 보관인 등록 뒤로가기 버튼 함수 추가
> feat: 주소 검색 페이지 추가 fix: 보관인등록 뒤로가기 개선, 보관소 등록에 주소검색 바인딩

- package-lock.json
- package.json
- src/pages/Chat/Chat.tsx
- src/pages/Chat/ChatroomList.tsx
- src/pages/Map/SearchAddress.tsx
- src/pages/Registration/Registration1.tsx
- src/pages/Registration/Registration2.tsx
- src/pages/Registration/Registration3.tsx
- src/pages/StorageList/StorageList.tsx
- src/routes/index.tsx
- src/services/ChatService.ts
fix: 채팅 시간 포맷 변환
fix: 보관소등록 데이터명 변경
fix: 보관소리스트 레이아웃 변경
1. 채팅 시간 포맷 형식 변경 (utc 00 -> moment timezone 활용)
2. 보관소 등록에서 데이터명 변경 (백엔드와의 통일성)
3. 보관소 등록 레이아웃 개선 (버튼이 짤리는것 -> 스크롤 가능하게 변경 and 위치 수정)
4. 보관소 리스트 레이아웃 변경 (오른쪽 짤리는 부분, 태그 필터 옆에 짤리는 부분)
> fix: 채팅 시간 포맷 변환 fix: 보관소등록 데이터명 변경 fix: 보관소리스트 레이아웃 변경

- public/index.html
- src/api/place.ts
- src/api/storage.ts
- src/components/map/KakaoMap.tsx
- src/constants/api.ts
- src/pages/Home/MapBottomSheet.tsx
- src/pages/Home/index.tsx
- src/pages/Map/SearchAddress.tsx
- src/pages/Registration/Registration1.tsx
- src/pages/Registration/Registration2.tsx
- src/pages/Registration/Registration3.tsx
- src/pages/StorageList/StorageFilterModal.tsx
- src/pages/StorageList/StorageList.tsx
- src/services/KakaoMapService.ts
- src/services/TagMappingService.ts
- src/utils/KakaoToDaum.ts
feat: 보관소 목록 조회 API 구현 fix: 보관소 목록 태그 개선 fix: 보관소 등록 데이터타입 개선
#56
1. 보관소 목록 조회 API 구현
2. 보관소 목록 태그 개선
3. 보관소 등록 데이터타입 개선
> feat: 보관소 목록 조회 API 구현 fix: 보관소 목록 태그 개선 fix: 보관소 등록 데이터타입 개선

- src/api/chat.ts
- src/api/client.ts
- src/api/storage.ts
- src/constants/api.ts
- src/pages/Chat/Chat.tsx
- src/services/ChatService.ts
> fix: API URL 변경

- src/constants/api.ts
> fix: api.ts 변경사항 반영

- src/api/place.ts
- src/api/storage.ts
- src/api/user.ts
- src/constants/api.ts
- src/pages/EditStorage/EditStorage.tsx
- src/pages/StorageDetail/StorageDetail.tsx
- src/utils/dataTransformers.ts
feat: 보관소 상세조회 api연결
feat: 내 거래내역 api연결
fix: 보관소 수정
feat: 보관소 수정 api연결
#54 
1. 보관소 상세조회 api 연결
2. 내 거래내역 api 연결
3. 보관소 수정 페이지 보관소 등록형식과 일치시키게 변경
4. 보관소 수정 api 연결
> feat: 보관소 상세조회 api연결 feat: 내 거래내역 api연결 fix: 보관소 수정 feat: 보관소 수정 api연결

- babel.config.js
- package-lock.json
- package.json
- src/pages/EditStorage/EditStorage.tsx
- src/services/api/modules/user.ts
> fix: 깃헙 액션1

- src/App.test.tsx
> fix: 깃헙 액션2

- src/App.tsx
- src/components/layout/MainLayout.tsx
- src/constants/routes.ts
- src/contexts/auth/index.tsx
- src/pages/EditStorage/EditStorage.tsx
- src/pages/Home/MapBottomSheet.tsx
- src/pages/Home/index.tsx
- src/pages/Login/KakaoCallback.tsx
- src/pages/MyPage/subpages/KeeperRegistration.tsx
- src/pages/MyPage/subpages/MyPlacePage.tsx
- src/pages/StorageList/StorageList.tsx
- src/routes/index.tsx
- src/utils/api/authUtils.ts
> fix: 라우팅 개선

- jest.config.js
- package-lock.json
- package.json
- src/App.test.tsx
- src/__mocks__/dateFnsMock.js
- src/pages/Chat/TradeConfirmModal.tsx
- src/services/api/modules/keeper.ts
> fix: 깃헙액션 테스트파일 추가 및 수정

- src/constants/api.ts
- src/pages/Chat/Chat.tsx
- src/services/ChatService.ts
- localStorage를 활용하여 새로고침 시에도 메시지 유지
- 웹소켓으로 받은 메시지도 로컬 스토리지에 저장
- 서버 메시지와 로컬 메시지 병합 및 중복 제거 로직 추가
- 사용자 입장 시스템 메시지 필터링
- 메시지 전송 후 즉시 UI에 표시되도록 개선
> fix: 채팅 메시지 저장 및 표시 기능 개선

- public/index.html
- src/components/feature/map/KakaoMap.tsx
- src/pages/MyPage/index.tsx
- src/pages/MyPage/subpages/StorageDetail.tsx
게시글 상세페이지 지도 표시 이슈 수정  
보관소 상세보기 - 채팅하기 버튼 레이아웃 조정  
채팅 중 새로고침 시 정렬 변경되는 문제 해결
> Rollback branch

- src/components/feature/map/KakaoMap.tsx
- src/pages/Registration/StorageRegistrationImages.tsx
1. 메인 게시글 주소 찍기
2. 게시판 등록 성공 시 라우팅되도록 수정
> [FIX] 메인 게시글 주소 찍기 + 게시판 등록 성공 시 라우팅

- src/pages/Registration/StorageRegistrationBasic.tsx
보관소 등록 시 희망 가격 입력 제한 
1. 보관소 등록 시 희망 가격 7자리로 제한
2. 입력 제한 관련 헬퍼텍스트 출력
> [FIX]보관소 등록 - 희망 가격 입력 제한

- src/services/ChatService.ts
메시지 타입 enum 수정
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> [FIX] 메시지 타입 enum 수정

- src/pages/Registration/StorageRegistrationImages.tsx
이미지 업로드 및 로컬스토리지 용량 제한 기능 추가
1. 이미지 업로드 및 로컬스토리지 용량 제한 기능 추가
> [FIX] 이미지 업로드 및 로컬스토리지 용량 제한 기능 추가

- src/constants/api.ts
- src/pages/Home/index.tsx
- src/services/api/modules/place.ts
- src/services/api/modules/trade.ts
메인 기능 수정
1. 특가 정보 조회 가능
2. API 조회 에러 응답 성공
** TODO
1. 최근 거래 내역 화면에 띄우기
2. coordinate 엔드포인트 삭제
3. 게시판 마커 다시 보기
> [FIX] 메인 기능 수정

- src/components/layout/MainLayout.tsx
- src/pages/EditStorage/EditStorageImages.tsx
- src/pages/Home/MainRedirect.tsx
- src/pages/Home/MapBottomSheet.tsx
- src/pages/Home/index.tsx
- src/pages/MyPage/subpages/KeeperRegistration.tsx
- src/pages/Registration/StorageRegistrationDetails.tsx
- src/pages/Registration/StorageRegistrationImages.tsx
fix: storage -> storages로 경로 다 수정
> fix: storage -> storages로 경로 다 수정

- src/pages/Chat/Chat.tsx
채팅 메시지의 정렬 순서와 스크롤 동작을 개선하여 사용자 경험을 향상시킵니다. 메시지가 시간순으로 올바르게 정렬되고, 새 메시지가 도착하거나 전송될 때 자동으로 하단으로 스크롤되도록 구현했습니다.
1. 메시지 정렬 로직 개선
- `groupMessagesByDate` 함수에서 메시지를 시간순으로 정렬하도록 수정
- 오래된 메시지가 위로, 새로운 메시지가 아래로 쌓이도록 변경
2. 스크롤 로직 단순화
- 불필요한 조건문 제거
- 중복된 스크롤 코드 통합
- 스크롤 동작을 'auto'로 설정하여 즉각적인 반응 구현
3. 자동 스크롤 기능 구현
- 새 메시지 도착 시 자동 하단 스크롤
- 메시지 전송 시 자동 하단 스크롤
- 컴포넌트 마운트 시 초기 스크롤 위치 설정
1. 메시지 정렬 테스트
- 여러 개의 메시지를 시간 순서대로 전송
- 메시지가 올바른 순서로 표시되는지 확인
- 날짜 구분선이 올바르게 표시되는지 확인
2. 스크롤 동작 테스트
- 새 메시지 전송 시 자동 스크롤 확인
- 새 메시지 수신 시 자동 스크롤 확인
- 채팅창에 처음 진입 시 최하단 스크롤 확인
3. 성능 테스트
- 많은 양의 메시지가 있을 때 스크롤 성능 확인
- 메시지 전송/수신 시 UI 반응성 확인
- 스크롤 동작은 사용자 경험을 고려하여 'auto'로 설정했습니다.
- 메시지 정렬은 서버에서 받은 시간 정보를 기준으로 합니다.
- 날짜 구분선은 메시지 시간이 변경될 때만 표시됩니다.
> fix: 채팅 메시지 정렬 및 스크롤 로직 개선

- src/components/layout/BottomNavigation.tsx
- src/pages/Home/index.tsx
- src/services/ChatService.ts
- last_message_time 기준으로 채팅방 목록을 최신순 정렬하도록 수정
- ChatService의 loadChatRooms 메서드에 정렬 로직 추가
- Date 객체를 사용하여 시간 비교 및 정렬 구현
> feat: 채팅방 목록 최신순 정렬 기능 추가

- src/pages/Home/LocationSearchModal.tsx
- src/pages/Home/MapBottomSheet.tsx
- src/pages/Home/index.tsx
- src/services/api/modules/place.ts
- 지도 게시글 마커 수정
- 하단 바 데이터 로딩(특가,거래내역) 로직 수정
1. place.ts
2. MapBottomSheet.tsx
3. LocationSearchModel.tsx
4. index.tsx
> [FIX] 지도 마커 수정

- src/pages/MyPage/index.tsx
- src/services/api/modules/image.ts
Resolves #이미지업로드-CORS
axios 전역 인터셉터를 우회하기 위한 plainAxios 인스턴스 도입
getPresignedUrl, moveImages 함수에서 plainAxios 사용
외부 presigned URL 업로드 후 이미지 정상 전송 및 렌더링 확인
마이페이지 닉네임 필드에 헬퍼 텍스트 (helperText) 관련 로직 추가
로컬 개발 환경에서 presigned URL 요청 테스트 (localhost:3000)
S3 업로드 후 백엔드 이미지 이동 요청 성공 확인
Chat 컴포넌트에서 이미지 전송 → 수신 → 화면 표시까지 플로우 검증 완료
마이페이지 닉네임 입력 시 헬퍼 텍스트 상태 업데이트 확인
> fix: S3 이미지 업로드 CORS 이슈 해결 및 마이페이지 헬퍼 텍스트 추가

- src/components/feature/map/KakaoMap.tsx
- src/pages/Home/index.tsx
- src/pages/Registration/StorageRegistrationImages.tsx
- 게시글 등록 주소 처리 로직 수정
- Home 현재 위치 버튼 로직 수정 (현재 수정 중)
1. KakaoMap.tsx
2. index.tsx
3. StorageRegistrationImage.tsx
> [FIX] 게시글 등록 주소 처리 로직 수정 + Home 현재위치 버튼 수정

- src/constants/api.ts
- src/pages/Login/KakaoCallback.tsx
- src/pages/Login/index.tsx
- src/pages/MyPage/index.tsx
- src/pages/MyPage/subpages/MyPlacePage.tsx
- src/services/api/modules/user.ts
fix: 마이페이지 닉네임변경 토큰 갱신 추가
fix: 로그인 <-> 메인페이지 무한 리디렉션 해결
fix: 로그인 요청 2번 나가는거 해결?
1.  마이페이지 닉네임변경 토큰 갱신 추가
2. 로그인 <-> 메인페이지 무한 리디렉션 해결
3. 로그인 요청 2번 나가는거 해결?
> fix: 마이페이지, 로그인

- src/constants/api.ts
> fix: redirect uri 수정

- .github/workflows/deploy-at-s3.yaml
fix: 진짜 deploy.yaml에 env 넣었으니 해결 완료?
제발...
> fix: 진짜 deploy.yaml에 env 넣었으니 해결 완료?

- public/index.html
> feat: GA4태그 추가

- src/pages/StorageList/StorageList.tsx
> fix: 필터 모달 active

- src/components/common/Modal.tsx
- src/components/layout/BottomNavigation.tsx
- src/pages/Chat/ChatroomList.tsx
- src/pages/Home/MapBottomSheet.tsx
- src/pages/MyPage/subpages/StorageDetail.tsx
- src/pages/StorageList/StorageList.tsx
> style: 주요색 변경

- src/pages/MyPage/index.tsx
- src/pages/MyPage/subpages/MyTradePage.tsx
닉네임 글자 수 최소 제한 2자 → 1자로 변경
특수문자 입력 제한을 위한 정규식 유효성 검사 도입
닉네임 유효성 검사 로직을 FE에 적용 및 에러 메시지 출력 추가
닉네임 1자 입력 시 유효성 통과 확인
특수문자 입력 시 에러 메시지 표시 확인
일반 텍스트 입력 시 정상 진행 여부 확인
> [FIX] 닉네임 유효성 검사 개선: 글자 수 및 특수문자 제한 추가

- src/pages/Chat/Chat.tsx
- src/services/api/modules/image.ts
fix: images 변경
이미지 요청 경로와 채팅에서 파일 확장자 제한
> fix: images 변경

- src/services/api/modules/image.ts
> fix: 이미지 업로드를 위한 axios 사용으로 변경

- src/pages/Chat/ChatroomList.tsx
마지막 메시지가 사진일 경우 사진을 보냈습니다 추가
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> feat: 사진을 보냈습니다 추가

- src/pages/EditStorage/EditStorageBasic.tsx
- src/pages/EditStorage/EditStorageDetails.tsx
- src/pages/EditStorage/EditStorageImages.tsx
- src/pages/Registration/StorageRegistrationBasic.tsx
- src/pages/Registration/StorageRegistrationDetails.tsx
- src/pages/Registration/StorageRegistrationImages.tsx
- 프로그레스 바 컨테이너의 마진을 중앙 정렬로 변경
- 버튼의 너비를 100%로 조정하고 최대 너비 설정
- 여러 컴포넌트에 flexbox 레이아웃 추가 및 정렬 개선
> style: 스타일 변경 및 레이아웃 조정

- src/components/feature/map/KakaoMap.tsx
- KakaoMap 컴포넌트에서 인포윈도우의 내용을 markerData.name으로 변경하여 주소 대신 이름을 표시하도록 수정
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
> fix: KakaoMap 인포윈도우 내용 수정

- public/index.html
> fix: 언어 설정을 한국어로 변경

- src/pages/Chat/ChatroomList.tsx
> [FIX] 채팅방 리스트 메시지 없을 때 제외
